name: ${CONTAINER_NAME:?container name is not defined...}
services:
  mysql:
    restart: ${RESTART:-no}
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./.env
    container_name: mysql-${CONTAINER_NAME:?container name is not defined...}
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/volumes/mysql/data:/var/lib/mysql:rw
      - ./docker/volumes/mysql/backups:/backups:rw

  dragonfly:
    restart: ${RESTART:-no}
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./.env
    container_name: dragonfly-${CONTAINER_NAME:?container name is not defined...}
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command: ["dragonfly", "--requirepass=${DRAGONFLY_PASS}", "--bind=0.0.0.0", "--port=6379"]
    ulimits:
      memlock: -1
    ports:
      - "${DRAGONFLY_PORT:-6379}:6379"
    volumes:
      - ./docker/volumes/dragonfly/data:/data:rw
      - ./docker/volumes/dragonfly/backups:/backups:rw

  mailhog:
    restart: ${RESTART:-no}
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./.env
    container_name: mailhog-${CONTAINER_NAME:?container name is not defined...}
    image: 'mailhog/mailhog:latest'
    ports:
        - '${MAILHOG_PORT:-1025}:1025'
        - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'